#
# dubboadmin2.5.4
#

FROM yi/centos7-tomcat7
MAINTAINER Yi.Ma <findlymw@gmail.com>


# RUN mkdir -p /usr/local/apache-tomcat-7.0.82/webapps/dubboadmin/

ADD dubbo-admin-2.8.4.zip /usr/local/apache-tomcat-7.0.82/webapps/dubboadmin
# WORKDIR /usr/local/apache-tomcat-7.0.82/webapps/dubboadmin/
# RUN jar -xvf  dubbo-admin-2.5.4.war
# RUN rm dubbo-admin-2.5.4.war